language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
# command to install dependencies
before_install:
  - pip install -e .
  - pip install nose coverage

# command to run tests
script:
  - nosetests --with-coverage --cover-package=tb_ioc
